### ISSUE TITLE
Fix README changes not appearing on documentation at https://solace.js.org

### ISSUE THREAD

**Issue by rustytrim** [solacejs/solace.js#6]
Currently in https://github.com/solacejs/solace.js/blob/main/website/src/app/page.tsx I just fetch the README from the repo so it can just refer to the README and have it show up on the vercel deployed website. However, it seems like it is only using an older version of the README. Not sure why, I am fetching from https://raw.githubusercontent.com/solacejs/solace.js/main/README.md  which should show all of the current README I think. It seems to have the same issues when the website is locally hosted as well. The website uses next.js if anyone is wondering. I do wonder if it could be some sort of overflow error as well, but probably not.

**Comment by ansh-saini** [comment]
Hi. I would like to work on this. Can you please assign this to me?

**Comment by rustytrim** [comment]
It looks like someone may have already fixed the issue though, I'll have to take a look at it later

**Comment by rustytrim** [comment]
Seems like the issues is still occurring for some reason, would you still like to work on it @ansh-saini

**Comment by ansh-saini** [comment]
The issue happens because GitHub has a 5 minute cache policy when new changes are pushed to the repository.
Either add a delay of 5 minutes in your build process, or find a way to import the readme file directly instead of accessing it via a URL.


I'll try to fix it once and for all.

**Comment by rustytrim** [comment]
Okay thank you, I'll look into adding a 5 minute delay into the build as well if I can

**Comment by ansh-saini** [comment]
No need to add the delay in the build process now. I found a way to bypass caching.

**Comment by rustytrim** [comment]
I noticed that just now. Learning new things about GitHub everyday, you can add a query string for token to fix the issue, thanks!
